import Config

config :changelogr, Changelogr.Repo,
  adapter: Ecto.Adapters.SQLite,
  database: System.get_env("DATABASE_URL")

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :changelogr, ChangelogrWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: 4000],
  url: [host: "localhost", port: 4000],
  server: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Changelogr.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
